# Generated by Django 2.2.12 on 2020-06-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tmc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_gt', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto mayor que')),
                ('monto_lt', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto menor que')),
                ('plazo_gt', models.IntegerField(verbose_name='Plazo mayor que')),
                ('plazo_lt', models.IntegerField(verbose_name='Plazo menor que')),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('tipo', models.IntegerField()),
            ],
        ),
    ]
