# Generated by Django 2.2.12 on 2020-06-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmc',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tmc',
            name='monto_lt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Monto menor que'),
        ),
        migrations.AlterField(
            model_name='tmc',
            name='plazo_lt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Plazo menor que'),
        ),
    ]
