# Generated by Django 2.2.12 on 2020-06-04 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreditApp', '0002_auto_20200602_2308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tmc',
        ),
    ]
